dist: bionic
language: java
jdk:
 - openjdk15
env:
 global:
  - secure: "M3R4J9V2u4V5rfbPTlLuGQvcSfmbRDFNuU/2tPqB9ilCZ2TuYPbIzxCeY2Phg46Fg3gbfGYIYp1Q2cCeB0Mx426e9qW4//DkNA9LkACr8om6vcfjHnKgjAmj74yksqJ6aegrdJh1uPMZzHsYfJ8NRFD3BksM2WpiuscsHrm7Mhk8qHhDl5WjVdN6INCHdz2lzJ+mmjOgRbZOPyUg/FnZjsQ9D7A/d3+pQ2jQ50sr3iFXY+LKiaJY3roP5qfQArdXUq371iN1UNVjgYenm2kUWno7GQ/IgRjzkgykYgN9O49xW/BuuRIWeO3y7ZuPVKeJKSqN2YdGt6huJjNoWIMFpPzebnoHodP8YfrWTB8bWWpNTi/w1E7som5tz6108aThXHPK6uhgAJ3VrUPVykZhOrFpsTrTSAkGeKHT+LO/vQmCSiapZuMmY/saPkrdPzF4n2sRe6TgpjXQ0NN48lvo6jgte/bbicaxryTxMOM3ortIsUXmq9rW4X2rAzWqbvB5nHJpklbNIxzTn78tMtfyu3hfqt8xl7YC4W8k7wbbjlS453ZKiPIh8HiuvQIR3QFmAlccih1yQD5MSRqNigU4F7iiYYu8OrFx2/uVANYEM4epXdBscqH4F8UPAG84pUrRvxmp6gkf0OPaFJVmZi90MYekrVpQWWy6A6yNFEQRp48="
cache:
 directories:
  - $HOME/.m2
script:
 - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
 - mvn -T 1C -f releng/edu.toronto.cs.se.modelepedia.libz3java.releng/pom.xml clean install
 - mvn -T 1C -f releng/edu.toronto.cs.se.mmint.releng/pom.xml clean install
after_success:
 - >
   test $TRAVIS_PULL_REQUEST = false &&
   git clone https://github.com/sscrane/sscrane.github.io.git &&
   cd sscrane.github.io &&
   rm -rf mmint/${TRAVIS_BRANCH/master/release} &&
   mv $TRAVIS_BUILD_DIR/releng/edu.toronto.cs.se.mmint.install/target/repository mmint/${TRAVIS_BRANCH/master/release} &&
   git add . &&
   git reset --soft HEAD~1 &&
   git commit --author="Sophie Crane <sscrane@smith.edu>" -m "mmint: Update builds" &&
   git push -f -q https://sscrane:$Token@github.com/sscrane/sscrane.github.io.git master &> /dev/null
  # Changed /sscrane/sscrane.github.io.git to sscrane/sscrane.github.io./MMINT/.git
  # Unsure how to connect to webpage